version: '3.8'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service
    command: ["./servicetest"]
    # Add other configurations like ports, volumes, etc. if needed

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: ["./apptest"]
    # Add other configurations like ports, volumes, etc. if needed
