version: '3.8'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service1
    command: ["./servicetest1"]
    # Add other configurations like ports, volumes, etc. if needed
  service2:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: service2
      command: ["./servicetest2"]
      # Add other configurations like ports, volumes, etc. if needed
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    command: ["./apptest1"]
    # Add other configurations like ports, volumes, etc. if needed
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    command: ["./apptest2"]
    # Add other configurations like ports, volumes, etc. if needed
